FROM comses/base:1.3.0

ENV DEBIAN_FRONTEND=noninteractive \
	LANG=C.UTF-8 \
	LC_ALL=C.UTF-8 \
	ANT_VERSION=1.10.13 \
    ANT_MIRROR=https://downloads.apache.org \
	ANT_HOME=/opt/ant

WORKDIR /tmp

RUN apt-get update && apt-get install -y --no-install-recommends openjdk-8-jdk wget
RUN wget --no-check-certificate --no-cookies ${ANT_MIRROR}/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz
RUN tar -zvxf apache-ant-${ANT_VERSION}-bin.tar.gz -C /opt/
RUN ln -sf /opt/apache-ant-${ANT_VERSION} /opt/ant
RUN rm -f apache-ant-${ANT_VERSION}-bin.tar.gz*
RUN update-alternatives --install /usr/bin/ant ant /opt/ant/bin/ant 1000
RUN rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y ca-certificates
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb http://download.mono-project.com/repo/ubuntu xenial main" | tee /etc/apt/sources.list.d/mono-official.list
RUN apt-get -y install mono-complete git
