name: Build Dotnet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  dotnet-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Create build
        run: bash docker-build-script.sh
        working-directory: docker
      
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: dist/
