name: Build Dotnet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dotnet-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Disable IPv6
        run: mkdir ~/.gnupg && echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf 
        
      - name: Create build
        run: bash docker-build-script.sh
        working-directory: docker
      
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: dist/
