name: Run .NET Tests

on:
  push:
    branches: [ dotnet_workflow ]

jobs:
  dotnet-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Check docker version
        run: bash docker-build-script.sh
        working-directory: sdk-csharp/docker

